map_tag_number_to_type = {
 
    '00' : 'EOC (End-of-Content)',
    '01' : 'BOOLEAN',
    '02' : 'INTEGER',
    '03' : 'BIT STRING',
    '04' : 'OCTET STRING',
    '05' : 'NULL',
    '06' : 'OBJECT IDENTIFIER',
    '07' : 'Object Descriptor',
    '08' : 'EXTERNAL',
    '09' : 'REAL (float)',
    '0A' : 'ENUMERATED',
    '0B' : 'EMBEDDED PDV',
    '0C' : 'UTF8String',
    '0D' : 'RELATIVE-OID',
    '0E' : '(reserved)',
    '0F' : '(reserved)',
    '10' : 'SEQUENCE and SEQUENCE OF',
    '11' : 'SET and SET OF',
    '12' : 'NumericString',
    '13' : 'PrintableString',
    '14' : 'T61String',
    '15' : 'VideotexString',
    '16' : 'IA5String',
    '17' : 'UTCTime',
    '18' : 'GeneralizedTime',
    '19' : 'GraphicString',
    '1A' : 'VisibleString',
    '1B' : 'GeneralString',
    '1C' : 'UniversalString',
    '1D' : 'CHARACTER STRING',
    '1E' : 'BMPString',
    '1F' : '(use long-form)',
    
}